### ISSUE TITLE
This script relies on Miniconda which can not be silently installed under a path with spaces. Press any key to continue . . .

### ISSUE THREAD

**Issue by breakingbadzy** [5PQR/TextAudioTool#1]
This script relies on Miniconda which can not be silently installed under a path with spaces.
Press any key to continue . . .

**Comment by 5PQR** [comment]
The script won't work if the path where it's in has spaces in it. That's due to a limitation in one of the tools it uses that needs paths to be in 7-bit ASCII (simple characters) and not use white spaces. 

So if you have "C:\My Folder\vam\" you'll have to rename the folder to something like "C:\My_Folder\vam\" to get it to work. VAM should still work the same if you rename the folder it's in,

**Comment by mk1027b** [comment]
Appreciate your great effort for the plugin, I am trying to get it work.

I got everything install properly, I hope so.. but it seemed that after clicking the "SEND MESSAGE" button  plugin UI in VAM, the bubble appears with "..." there is nothing much shown in the console.

Below is the KOBOLD link pulgin:

KoboldLink preferences loaded
Atom type: Person
Audiofile path:TextAudioTool-0.4/SPQR.TextAudioTool/files/tts_output.wav
{"max_context_length": 2048, "max_length": 100,"memory":"You are in a never ending roleplay and play a role of the Olivia character. You are in a dialogue with Musa. Below is the description of the Olivia character.\n\nOlivia is a Latina girl with tanned skin and a nice figure. Brunette. Cup size B. She is relaxing on a secluded tropical beach and is ready to have a good intimate time with her boyfriend Musa to the measured sound of the sea waves in the rays of the setting tropical sun.\n\n[Author's note: Keep the roleplay. Your response must contain only the Olivia's short chat-style answer (one or two sentences) to Musa and nothing else. Don't use any emoji.]\n\n", "prompt":"\n### Instruction:\nHello! How are you recently?\n### Response:\n", "quiet":"true", "stop_sequence":["### Instruction:", "### Response:"], "rep_pen": 1.1, "rep_pen_range": 256, "rep_pen_slope": 1, "temperature": 0.5, "tfs": 1, "top_a": 0, "top_k": 100, "top_p": 0.9, "typical": 1}
Kobold Processing succeeded
**Error: Error: ConnectFailure (Connection Refuse)**
)

My install path is D:\VM\VAM\TextAudioTool-0.4\SPQR.TextAudioTool\
I ran the SPQR.TextAudioTool - (standalone) bat file in the \TextAudioTool-0.4\ folder. It is not able to run in the folder where VAM.exe exist. Could this be the reason?


COMMAND PROMPT:

    127.0.0.1:7069/userelevenlabs GET - gets elevenlabs user available tokens count
    127.0.0.1:7069/modelselevenlabs GET - gets elevenlabs available AI models
    127.0.0.1:7069/voiceselevenlabs GET - gets elevenlabs available voices
    More details and endpoint tests in demo/demo.html
------------------------------------------------------------------------------
    Help me make more cool stuff at: patreon.com/spqr_aeternum
==============================================================================
Checking ffmpeg ...
    ffmpeg is installed. Proceeding with the script...
    pyttsx3 is already installed.
    SpeechRecognition Checking...
    Package ok: SpeechRecognition!
    pocketsphinx is already installed.
    PyAudio Checking...
    Package ok: PyAudio!
    pysoundfile Checking...
    Package ok: pysoundfile!
    openai-whisper Checking...
    Package ok: openai-whisper!
    Checking for Whisper model...
D:\VM\VAM\TextAudioTool-0.4\SPQR.TextAudioTool\installer_files\env\lib\site-packages\whisper\__init__.py:146: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
==============================================================================
              ██████  ███████  █████  ██████  ██    ██ ██
              ██   ██ ██      ██   ██ ██   ██  ██  ██  ██
              ██████  █████   ███████ ██   ██   ████   ██
              ██   ██ ██      ██   ██ ██   ██    ██
              ██   ██ ███████ ██   ██ ██████     ██    ██
------------------------------------------------------------------------------
    Listening for incoming requests...
