### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by Zerokiryu777** [5PQR/TextAudioTool#4]
When running the bat file, this error comes out, how do I fix it?

    Checking for Whisper model...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

**Comment by 5PQR** [comment]
try v0.4, should fix that issue

**Comment by Zerokiryu777** [comment]
Its working now, thank you for the update ^^
