### ISSUE TITLE
There is a connection error in the plugin console and only "..." appears in the text bubble.

### ISSUE THREAD

**Issue by mk1027b** [5PQR/TextAudioTool#5]
Appreciate your great effort for the plugin, I am trying to get it work.

I got everything install properly, I hope so.. but it seemed that after clicking the "SEND MESSAGE" button plugin UI in VAM, the bubble appears with "..." there is nothing much shown in the console.

Below is the KOBOLD link pulgin:

KoboldLink preferences loaded
Atom type: Person
Audiofile path:TextAudioTool-0.4/SPQR.TextAudioTool/files/tts_output.wav
{"max_context_length": 2048, "max_length": 100,"memory":"You are in a never ending roleplay and play a role of the Olivia character. You are in a dialogue with Musa. Below is the description of the Olivia character.\n\nOlivia is a Latina girl with tanned skin and a nice figure. Brunette. Cup size B. She is relaxing on a secluded tropical beach and is ready to have a good intimate time with her boyfriend Musa to the measured sound of the sea waves in the rays of the setting tropical sun.\n\n[Author's note: Keep the roleplay. Your response must contain only the Olivia's short chat-style answer (one or two sentences) to Musa and nothing else. Don't use any emoji.]\n\n", "prompt":"\n### Instruction:\nHello! How are you recently?\n### Response:\n", "quiet":"true", "stop_sequence":["### Instruction:", "### Response:"], "rep_pen": 1.1, "rep_pen_range": 256, "rep_pen_slope": 1, "temperature": 0.5, "tfs": 1, "top_a": 0, "top_k": 100, "top_p": 0.9, "typical": 1}
Kobold Processing succeeded
**Error: Error: ConnectFailure (Connection Refuse)**
)

My install path is D:\VM\VAM\TextAudioTool-0.4\SPQR.TextAudioTool
I ran the SPQR.TextAudioTool - (standalone) bat file in the \TextAudioTool-0.4\ folder. It is not able to run in the folder where VAM.exe exist. Could this be the reason? I also check the demo page 

Boxes are all Green: Response:
{"status":"running"}
"TTS_MS_EN-US_ZIRA_11.0":"Microsoft Zira Desktop - English (United States)"}
status":"ok","text":"brand new brand new brand new brand new brand new bread to know for the new brand new brand new bread nero","error":""
"status":"error","text":"","error":"An error occurred: listening timed out while waiting for phrase to start"}

COMMAND PROMPT:

127.0.0.1:7069/userelevenlabs GET - gets elevenlabs user available tokens count
127.0.0.1:7069/modelselevenlabs GET - gets elevenlabs available AI models
127.0.0.1:7069/voiceselevenlabs GET - gets elevenlabs available voices
More details and endpoint tests in demo/demo.html
Help me make more cool stuff at: patreon.com/spqr_aeternum
==============================================================================
Checking ffmpeg ...
ffmpeg is installed. Proceeding with the script...
pyttsx3 is already installed.
SpeechRecognition Checking...
Package ok: SpeechRecognition!
pocketsphinx is already installed.
PyAudio Checking...
Package ok: PyAudio!
pysoundfile Checking...
Package ok: pysoundfile!
openai-whisper Checking...
Package ok: openai-whisper!
Checking for Whisper model...
D:\VM\VAM\TextAudioTool-0.4\SPQR.TextAudioTool\installer_files\env\lib\site-packages\whisper_init_.py:146: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
checkpoint = torch.load(fp, map_location=device)
          ██████  ███████  █████  ██████  ██    ██ ██
          ██   ██ ██      ██   ██ ██   ██  ██  ██  ██
          ██████  █████   ███████ ██   ██   ████   ██
          ██   ██ ██      ██   ██ ██   ██    ██
          ██   ██ ███████ ██   ██ ██████     ██    ██
Listening for incoming requests...

**Comment by 5PQR** [comment]
I don't think your problems are related to the work here, if you see READY and no errors after that then this should be good.

1. I think the creator of that plugin uses v0.2 of this tool, you're trying to use v0.4 which might not be supported by the KoboldLink plugin
2. the error "Error: Error: ConnectFailure (Connection Refuse)" suggests to me that you didn't enable the API in kobold, and koboldlink can't communicate with it. You should follow the instructions from KoboldLink on how to enable the API, and make sure it works. By default it's probably off. I haven't used Kobold in over a year so I'm not sure
3. To be sure, you can go to this http://127.0.0.1:7069/status in a browser when TextAudioTool is running. If you get status:running, then this tool is good. If you get some browser error, then maybe your PC is using that port for something else or you have something block the tool from using that port and then KoboldLink can't connect to it. But it's very unlikely the case, most likely 2 is your problem

**Comment by mk1027b** [comment]
You are absolutely right. It's point 2 above. I had not enable the API.. http://127.0.0.1:7069/status is running. I can also hear the voice speaking back after a while. 

Thanks and appreciate your response and help!
